name: A Linguagem de Programação Crystal
description: Uma linguagem compilada com sintaxe parecida com Ruby e inferência de tipos
url: http://br.crystal-lang.org
logo: /images/crystal-h.png
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      image: /images/icon.png
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      image: /images/icon.png
      layout: post
twitter:
  username: CrystalLanguage

highlighter: rouge
markdown: kramdown
exclude: ["*.haml", "Gemfile", "Gemfile.lock", "Rakefile", "travis-build.sh", "scripts/*.cr"]
gems:
  - jekyll-seo-tag
